### ISSUE TITLE
On macOS Sierra 10.12, `fkill --force` by process name throws exception because `pkill` does not support `-9` flag

### ISSUE THREAD

**Issue by sompylasar** [sindresorhus/fkill#24]
```
$ fkill --force node
AggregateError: 
    Error: Killing process node failed: pkill: illegal option -- 9
    usage: pkill [-signal] [-ILfilnovx] [-F pidfile] [-G gid]
                 [-P ppid] [-U uid] [-g pgrp]
                 [-t tty] [-u euid] pattern ...
        at Array.map (<anonymous>)
        at processExists.all.then.then (/Users/ivanbabak/.nvm/versions/node/v8.7.0/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
        at <anonymous>
    at processExists.all.then.then (/Users/ivanbabak/.nvm/versions/node/v8.7.0/lib/node_modules/fkill-cli/node_modules/fkill/index.js:83:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

https://github.com/sindresorhus/fkill/blob/23503ecce18b5685c18458055efd20c6d2e62238/index.js#L16-L23

**Comment by sindresorhus** [comment]
Not interested in supporting macOS 10.12.
