### ISSUE TITLE
pkill: illegal option -- 9

### ISSUE THREAD

**Issue by Turbo87** [sindresorhus/fkill#40]
It seems that the `-f` option isn't quite working for me:

```
$ fkill -f ember
AggregateError: 
    Error: Killing process ember failed: pkill: illegal option -- 9
    usage: pkill [-signal] [-ILfilnovx] [-F pidfile] [-G gid]
                 [-P ppid] [-U uid] [-g pgrp]
                 [-t tty] [-u euid] pattern ...
        at Array.map (<anonymous>)
        at fkill (/Users/tbieniek/.volta/tools/image/packages/fkill-cli/6.0.1/node_modules/fkill/index.js:124:9)
    at fkill (/Users/tbieniek/.volta/tools/image/packages/fkill-cli/6.0.1/node_modules/fkill/index.js:124:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm running this on macOS 10.14 with the `fish` shell, in case it matters.

**Comment by Turbo87** [comment]
using `kill -9 PID` seems to work though, so maybe it's just using the wrong tool? 🤔

**Comment by sindresorhus** [comment]
I think https://github.com/sindresorhus/fkill/blob/fbbf525c93426f5398cc527764b43d689c7d5e3b/index.js#L37 needs to be changed to `-signal` with the equivalent value.
