### ISSUE TITLE
Cannot install on Zorin 16 (Ubuntu 20.04. 2 LTS)

### ISSUE THREAD

**Issue by PrzemekSkw** [sindresorhus/fkill#57]
I cannot install on Zorin. I try two commands: `npm install fkill` and `npm install --global fkill-cli`. I install nodejs and npm before.
```
npm install fkill
[..................] - rollbackFailedOptional: verb npm-session ed90483d122539e
npm WARN saveError ENOENT: no such file or directory, open '/home/emi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for fkill@8.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill@8.0.0
npm WARN notsup Unsupported engine for aggregate-error@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: aggregate-error@4.0.0
npm WARN notsup Unsupported engine for taskkill@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: taskkill@4.0.0
npm WARN notsup Unsupported engine for pid-port@0.2.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pid-port@0.2.0
npm WARN notsup Unsupported engine for clean-stack@4.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: clean-stack@4.1.0
npm WARN notsup Unsupported engine for indent-string@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: indent-string@5.0.0
npm WARN notsup Unsupported engine for escape-string-regexp@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: escape-string-regexp@5.0.0
npm WARN notsup Unsupported engine for arrify@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: arrify@3.0.0
npm WARN enoent ENOENT: no such file or directory, open '/home/emi/package.json'
npm WARN emi No description
npm WARN emi No repository field.
npm WARN emi No README data
npm WARN emi No license field.

+ fkill@8.0.0
added 27 packages from 7 contributors and audited 27 packages in 6.123s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

emi@emilka-matebook:~$ 
emi@emilka-matebook:~$ fkill

Polecenie 'fkill' nie zostało znalezione, ale można je zainstalować za pomocą:

sudo snap install fkill

emi@emilka-matebook:~$ sudo npm install fkill
npm WARN saveError ENOENT: no such file or directory, open '/home/emi/package.json'
npm WARN notsup Unsupported engine for fkill@8.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill@8.0.0
npm WARN enoent ENOENT: no such file or directory, open '/home/emi/package.json'
npm WARN emi No description
npm WARN emi No repository field.
npm WARN emi No README data
npm WARN emi No license field.

+ fkill@8.0.0
updated 1 package and audited 48 packages in 0.856s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

emi@emilka-matebook:~$ npm install --global fkill-cli
npm WARN checkPermissions Missing write access to /usr/local/lib
npm WARN notsup Unsupported engine for fkill-cli@7.0.0: wanted: {"node":"^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill-cli@7.0.0
npm WARN notsup Unsupported engine for pid-port@0.2.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pid-port@0.2.0
npm WARN notsup Unsupported engine for fkill@8.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill@8.0.0
npm WARN notsup Unsupported engine for cli-truncate@3.1.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cli-truncate@3.1.0
npm WARN notsup Unsupported engine for meow@10.1.2: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: meow@10.1.2
npm WARN notsup Unsupported engine for esc-exit@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esc-exit@3.0.0
npm WARN notsup Unsupported engine for num-sort@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: num-sort@3.0.0
npm WARN notsup Unsupported engine for slice-ansi@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: slice-ansi@5.0.0
npm WARN notsup Unsupported engine for string-width@5.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: string-width@5.0.1
npm WARN notsup Unsupported engine for ansi-styles@6.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-styles@6.1.0
npm WARN notsup Unsupported engine for is-fullwidth-code-point@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: is-fullwidth-code-point@4.0.0
npm WARN notsup Unsupported engine for strip-ansi@7.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: strip-ansi@7.0.1
npm WARN notsup Unsupported engine for ansi-regex@6.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-regex@6.0.1
npm WARN notsup Unsupported engine for aggregate-error@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: aggregate-error@4.0.0
npm WARN notsup Unsupported engine for taskkill@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: taskkill@4.0.0
npm WARN notsup Unsupported engine for clean-stack@4.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: clean-stack@4.1.0
npm WARN notsup Unsupported engine for indent-string@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: indent-string@5.0.0
npm WARN notsup Unsupported engine for escape-string-regexp@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: escape-string-regexp@5.0.0
npm WARN notsup Unsupported engine for arrify@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: arrify@3.0.0
npm WARN notsup Unsupported engine for read-pkg-up@8.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: read-pkg-up@8.0.0
npm WARN notsup Unsupported engine for camelcase-keys@7.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: camelcase-keys@7.0.1
npm WARN notsup Unsupported engine for redent@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: redent@4.0.0
npm WARN notsup Unsupported engine for trim-newlines@4.0.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: trim-newlines@4.0.2
npm WARN notsup Unsupported engine for read-pkg@6.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: read-pkg@6.0.0
npm WARN notsup Unsupported engine for strip-indent@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: strip-indent@4.0.0

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emi/.npm/_logs/2021-12-05T08_55_44_196Z-debug.log
emi@emilka-matebook:~$ sudo npm install --global fkill-cli
/usr/local/bin/fkill -> /usr/local/lib/node_modules/fkill-cli/cli.js
npm WARN notsup Unsupported engine for fkill-cli@7.0.0: wanted: {"node":"^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill-cli@7.0.0
npm WARN notsup Unsupported engine for fkill@8.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fkill@8.0.0
npm WARN notsup Unsupported engine for meow@10.1.2: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: meow@10.1.2
npm WARN notsup Unsupported engine for esc-exit@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: esc-exit@3.0.0
npm WARN notsup Unsupported engine for pid-port@0.2.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pid-port@0.2.0
npm WARN notsup Unsupported engine for num-sort@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: num-sort@3.0.0
npm WARN notsup Unsupported engine for cli-truncate@3.1.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cli-truncate@3.1.0
npm WARN notsup Unsupported engine for slice-ansi@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: slice-ansi@5.0.0
npm WARN notsup Unsupported engine for string-width@5.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: string-width@5.0.1
npm WARN notsup Unsupported engine for ansi-styles@6.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-styles@6.1.0
npm WARN notsup Unsupported engine for is-fullwidth-code-point@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: is-fullwidth-code-point@4.0.0
npm WARN notsup Unsupported engine for strip-ansi@7.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: strip-ansi@7.0.1
npm WARN notsup Unsupported engine for ansi-regex@6.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-regex@6.0.1
npm WARN notsup Unsupported engine for aggregate-error@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: aggregate-error@4.0.0
npm WARN notsup Unsupported engine for taskkill@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: taskkill@4.0.0
npm WARN notsup Unsupported engine for indent-string@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: indent-string@5.0.0
npm WARN notsup Unsupported engine for clean-stack@4.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: clean-stack@4.1.0
npm WARN notsup Unsupported engine for escape-string-regexp@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: escape-string-regexp@5.0.0
npm WARN notsup Unsupported engine for arrify@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: arrify@3.0.0
npm WARN notsup Unsupported engine for trim-newlines@4.0.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: trim-newlines@4.0.2
npm WARN notsup Unsupported engine for read-pkg-up@8.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: read-pkg-up@8.0.0
npm WARN notsup Unsupported engine for redent@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: redent@4.0.0
npm WARN notsup Unsupported engine for camelcase-keys@7.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: camelcase-keys@7.0.1
npm WARN notsup Unsupported engine for read-pkg@6.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: read-pkg@6.0.0
npm WARN notsup Unsupported engine for strip-indent@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: strip-indent@4.0.0

+ fkill-cli@7.0.0
added 153 packages from 100 contributors in 12.696s
emi@emilka-matebook:~$ fkill
/usr/local/lib/node_modules/fkill-cli/cli.js:2
import process from 'node:process';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
Regards.

**Comment by sindresorhus** [comment]
I think the error message is pretty clear:

> npm WARN notsup Not compatible with your version of node/npm
